### ISSUE TITLE
VSPICLK_OUT_MUX_IDX was removed 

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp32-nesemu#4]
hi

since last esp-idf update there was a remove/change 

https://github.com/espressif/esp-idf/commit/23455de4c2f6f8308f60d11badf4a95ed644bd57#diff-da26bb48d6c7dd629da1e755d7283f29L138

only for info:
if we add in  components/esp32/include/soc/gpio_sig_map.h
`#define VSPICLK_OUT_MUX_IDX			63`

then compile is ok, 
other side

...... /components/nofrendo-esp32/spi_lcd.c:263:34: error: 'VSPICLK_OUT_MUX_IDX' undeclared (first use in this function)
     gpio_matrix_out(PIN_NUM_CLK, VSPICLK_OUT_MUX_IDX,0,0);

https://github.com/espressif/esp32-nesemu/blob/master/components/nofrendo-esp32/spi_lcd.c#L253

best wishes
rudi ;-)

**Comment by Spritetm** [comment]
Yeah, I should spend a few moments to fix up the NES emu to the new SPI driver as well... makes the code cleaner. Maybe I can also implement sound; we have a I2S driver as well now.

**Comment by ESP32DE** [comment]
> Maybe I can also implement sound;

**callback :)** 
does you have had perhabs a small time to do this or perhabs can get small time for it?
;-)
