### ISSUE TITLE
crash..

### ISSUE THREAD

**Issue by 0x1abin** [espressif/esp32-nesemu#8]
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0010,len:4
load:0x3fff0014,len:7380
load:0x40078000,len:0
load:0x40078000,len:14024
entry 0x400792fc
[0;32mI (47) boot: ESP-IDF v3.0-dev-245-gb8b553d1-dirty 2nd stage bootloader[0m
[0;32mI (47) boot: compile time 18:26:39[0m
[0;32mI (59) boot: Enabling RNG early entropy source...[0m
D (109) bootloader_flash: mmu set block paddr=0x00000000 (was 0xffffffff)[0m
D (172) boot: magic e9[0m
D (194) boot: segments 04[0m
D (219) boot: spi_mode 02[0m
D (244) boot: spi_speed 00[0m
D (270) boot: spi_size 02[0m
[0;32mI (295) boot: SPI Speed      : 40MHz[0m
[0;32mI (334) boot: SPI Mode       : DIO[0m
[0;32mI (371) boot: SPI Flash Size : 4MB[0m
D (409) bootloader_flash: mmu set paddr=00000000 count=1[0m
D (459) boot: mapped partition table 0x8000 at 0x3f408000[0m
D (509) flash_parts: partition table verified, 4 entries[0m
[0;32mI (559) boot: Partition Table:[0m
[0;32mI (593) boot: ## Label            Usage          Type ST Offset   Length[0m
D (662) boot: load partition table entry 0x3f408000[0m
D (707) boot: type=1 subtype=2[0m
[0;32mI (736) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
D (806) boot: load partition table entry 0x3f408020[0m
D (851) boot: type=1 subtype=1[0m
[0;32mI (880) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
D (950) boot: load partition table entry 0x3f408040[0m
D (996) boot: type=0 subtype=0[0m
[0;32mI (1024) boot:  2 factory          factory app      00 00 00010000 000e0000[0m
D (1095) boot: load partition table entry 0x3f408060[0m
D (1141) boot: type=40 subtype=1[0m
[0;32mI (1172) boot:  3 nesgame          unknown          40 01 00100000 00300000[0m
[0;32mI (1243) boot: End of partition table[0m
[0;32mI (1282) boot: Disabling RNG early entropy source...[0m
[0;32mI (1335) boot: Loading app partition at offset 00010000[0m
D (1389) esp_image: reading image header @ 0x10000[0m
D (1434) bootloader_flash: mmu set block paddr=0x00010000 (was 0xffffffff)[0m
D (1498) esp_image: image header: 0xe9 0x07 0x02 0x02 40080d3c[0m
V (1552) esp_image: loading segment header 0 at offset 0x10018[0m
V (1607) esp_image: segment data length 0x6404 data starts 0x10020[0m
V (1665) esp_image: segment 0 map_segment 1 segment_data_offs 0x10020 load_addr 0x3f400020[0m
[0;32mI (1742) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x06404 ( 25604) map[0m
D (1824) bootloader_flash: mmu set paddr=00010000 count=1[0m
V (1922) esp_image: loading segment header 1 at offset 0x16424[0m
D (1929) bootloader_flash: mmu set block paddr=0x00010000 (was 0xffffffff)[0m
V (1993) esp_image: segment data length 0x2e24 data starts 0x1642c[0m
V (2051) esp_image: segment 1 map_segment 0 segment_data_offs 0x1642c load_addr 0x3ffb0000[0m
[0;32mI (2128) esp_image: segment 1: paddr=0x0001642c vaddr=0x3ffb0000 size=0x02e24 ( 11812) load[0m
D (2211) bootloader_flash: mmu set paddr=00010000 count=1[0m
V (2285) esp_image: loading segment header 2 at offset 0x19250[0m
D (2316) bootloader_flash: mmu set block paddr=0x00010000 (was 0xffffffff)[0m
V (2380) esp_image: segment data length 0x400 data starts 0x19258[0m
V (2437) esp_image: segment 2 map_segment 0 segment_data_offs 0x19258 load_addr 0x40080000[0m
[0;32mI (2514) esp_image: segment 2: paddr=0x00019258 vaddr=0x40080000 size=0x00400 (  1024) load[0m
D (2597) bootloader_flash: mmu set paddr=00010000 count=1[0m
V (2650) esp_image: loading segment header 3 at offset 0x19658[0m
D (2702) bootloader_flash: mmu set block paddr=0x00010000 (was 0xffffffff)[0m
V (2766) esp_image: segment data length 0x69b0 data starts 0x19660[0m
V (2824) esp_image: segment 3 map_segment 0 segment_data_offs 0x19660 load_addr 0x40080400[0m
[0;32mI (2901) esp_image: segment 3: paddr=0x00019660 vaddr=0x40080400 size=0x069b0 ( 27056) load[0m
D (2984) bootloader_flash: mmu set paddr=00010000 count=2[0m
V (3090) esp_image: loading segment header 4 at offset 0x20010[0m
D (3090) bootloader_flash: mmu set block paddr=0x00020000 (was 0xffffffff)[0m
V (3153) esp_image: segment data length 0x2531c data starts 0x20018[0m
V (3212) esp_image: segment 4 map_segment 1 segment_data_offs 0x20018 load_addr 0x400d0018[0m
[0;32mI (3289) esp_image: segment 4: paddr=0x00020018 vaddr=0x400d0018 size=0x2531c (152348) map[0m
D (3371) bootloader_flash: mmu set paddr=00020000 count=3[0m
V (3703) esp_image: loading segment header 5 at offset 0x45334[0m
D (3704) bootloader_flash: mmu set block paddr=0x00040000 (was 0xffffffff)[0m
V (3718) esp_image: segment data length 0x8b0 data starts 0x4533c[0m
V (3775) esp_image: segment 5 map_segment 0 segment_data_offs 0x4533c load_addr 0x40086db0[0m
[0;32mI (3852) esp_image: segment 5: paddr=0x0004533c vaddr=0x40086db0 size=0x008b0 (  2224) load[0m
D (3935) bootloader_flash: mmu set paddr=00040000 count=1[0m
V (3991) esp_image: loading segment header 6 at offset 0x45bec[0m
D (4040) bootloader_flash: mmu set block paddr=0x00040000 (was 0xffffffff)[0m
V (4104) esp_image: segment data length 0x0 data starts 0x45bf4[0m
V (4160) esp_image: segment 6 map_segment 0 segment_data_offs 0x45bf4 load_addr 0x400c0000[0m
[0;32mI (4237) esp_image: segment 6: paddr=0x00045bf4 vaddr=0x400c0000 size=0x00000 (     0) load[0m
D (4320) bootloader_flash: mmu set paddr=00040000 count=1[0m
V (4371) esp_image: image start 0x00010000 end of last section 0x00045bf4[0m
D (4434) bootloader_flash: mmu set block paddr=0x00040000 (was 0xffffffff)[0m
D (4498) esp_image: Calculated hash: 706e43cd[0m
D (4539) bootloader_flash: mmu set paddr=00040000 count=1[0m
D (4604) boot: Mapping segment 0 as IROM[0m
D (4626) boot: Mapping segment 4 as DROM[0m
D (4663) boot: calling set_cache_and_start_app[0m
D (4704) boot: configure drom and irom and start[0m
V (4748) boot: d mmu set paddr=00020000 vaddr=400d0000 size=152348 n=3[0m
V (4809) boot: rc=0[0m
V (4829) boot: rc=0[0m
V (4849) boot: i mmu set paddr=00010000 vaddr=3f400000 size=25604 n=1[0m
V (4909) boot: rc=0[0m
V (4929) boot: rc=0[0m
D (4949) boot: start: 0x40080d3c[0m
[0;32mI (4980) cpu_start: Pro cpu up.[0m
[0;32mI (5015) cpu_start: Starting app cpu, entry point is 0x40080cf4[0m
[0;32mI (5076) cpu_start: App cpu up.[0m
[0;32mI (5114) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (5178) heap_init: At 3FFAE2A0 len 00001D60 (7 KiB): DRAM[0m
[0;32mI (5235) heap_init: At 3FFB7D48 len 000282B8 (160 KiB): DRAM[0m
[0;32mI (5293) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
[0;32mI (5353) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
[0;32mI (5413) heap_init: At 40087660 len 000189A0 (98 KiB): IRAM[0m
[0;32mI (5471) cpu_start: Pro cpu start user code[0m
D (5582) clk: RTC_SLOW_CLK calibration value: 3313293[0m
V (5668) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): checking args[0m
V (5668) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): Args okay. Resulting flags 0xE[0m
D (5718) intr_alloc: Connected src 46 to int 2 (cpu 0)[0m
V (5769) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): checking args[0m
V (5824) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): Args okay. Resulting flags 0x40E[0m
D (5900) intr_alloc: Connected src 24 to int 3 (cpu 0)[0m
[0;32mI (5950) cpu_start: Starting scheduler on PRO CPU.[0m
V (6000) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): checking args[0m
V (6006) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): Args okay. Resulting flags 0x40E[0m
D (6014) intr_alloc: Connected src 25 to int 2 (cpu 1)[0m
[0;32mI (6019) cpu_start: Starting scheduler on APP CPU.[0m
NoFrendo start!
lcd spi pin mux init ...
lcd spi signal init
Hspi config
PSX controller disabled in menuconfig; no input enabled.
Malloc: 916 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/./bitmap.c:47
video driver: Simple DirectMedia Layer at 256x224
vid_init done
vid_init done
Malloc: 4 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/./nofrendo.c:243
Malloc: 4 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/./nofrendo.c:152
system type unknown, playing nofrendo NES intro.
Malloc: 4 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/./nofrendo.c:152
Malloc: 824 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/nes/nes.c:511
Malloc: 65283 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/./bitmap.c:84
Malloc: 980 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/./bitmap.c:47
Malloc: 92 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/nes/nes.c:526
Malloc: 2048 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/nes/nes.c:533
Malloc: 368 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/sndhrdw/nes_apu.c:1002
Malloc: 7608 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/nes/nes_ppu.c:128
Initialized. ROM@0x3f410000
Malloc: 1068 at /Users/Zibin/workspace/esp/esp32-nesemu/components/nofrendo/nes/nes_rom.c:444
Head: 0x3f410000 (ff ff ff ff)
GUI:  is not a valid ROM image
GUI: ROM freed
GUI: ROM not loaded
NoFrendo died? WtF?
Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception)
Debug exception reason: BREAKN instr 
Register dump:
PC      : 0x400d239b  PS      : 0x00060b36  A0      : 0x80082f35  A1      : 0x3ffbac90  
A2      : 0x00000005  A3      : 0x00000005  A4      : 0x00060023  A5      : 0x3ffaf6cc  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x800d1d74  A9      : 0x3ffbac70  
A10     : 0x0000000a  A11     : 0x00000000  A12     : 0x3ffb2eb4  A13     : 0x3ffbb880  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000004  EXCCAUSE: 0x00000001  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffa  

Backtrace: 0x400d239b:0x3ffbac90 0x40082f32:0x3ffbacb0

**Comment by Spritetm** [comment]
>  GUI: is not a valid ROM image

In other words: you need a valid game rom in flash to use this.
